version: '2'
services:
    sampleapp-app:
        image: sampleapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sampleapp-postgresql:5432/sampleapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sampleapp-postgresql:
        extends:
            file: postgresql.yml
            service: sampleapp-postgresql
